[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10"
borsh-derive = "0.10"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
hex = "0.4"



[dev-dependencies]
rand = "0.8"
